const projectData = [
  {
    id: 4,
    localURL: 'personal-blog',
    componentName: 'PersonalBlog',
    url: 'http://www.mareksadecky.com',
    github: 'http://www.github.com',
    demo: 'www.mcrev.sk',
    facebook: 'Put-link-here',
    linkedin: 'https://www.linkedin.com/in/mrksc/',
    codePen: 'Put-link-here',
    thumbnail: 'port-thub-four.jpg',
    heading: 'Personal Blog MRKSC',
    subHeading: 'React, fullpage.js, contact form',
    excerpt: 'My personal blog app with contact form which provided for me a interesting look at combination of two technologies i like the most. Frontend React and Server side Node.js. The App is served from Express server. Project is deployed to Heroku and domain is hotest on Websupport. All design here is designed by me. In the future i want to have here a blog where i can express some topics i like. The portfolio section use a Fullpage React module. All my projects and information will be posted here as portfolio',
    author: 'MRKSC',
    published: '20.2.2020',
    skills: {
      node: 'on',
      react: 'on',
      wordpress: '',
      server: 'on',
      database: '',
      javascript: 'on',
      google: 'on',
      css: 'on',
    },
  },
  {
    id: 1,
    localURL: 'wordpress-website',
    componentName: 'WordpressSite',
    url: 'http://www.mcrev.sk',
    github: 'http://www.github.com',
    demo: 'www.mcrev.sk',
    facebook: 'Put-link-here',
    linkedin: 'https://www.linkedin.com/in/mrksc/',
    codePen: 'Put-link-here',
    thumbnail: 'port-thub-one.jpg',
    heading: 'A Wordpress website',
    subHeading: 'Design, content, google API',
    excerpt: 'A website for a client build on a Wordpress platform for easy adjustment and content management for a user. I did here a integration of Google API for Map service and Analytics. Project is hosted on Websupport hosting. Domain registration and setup of a email client...  Integration of Google API for Map service and analytics. The design of a page is builded with help of a theme from Avada purchased at Themeforest. Overal functionality of a web is to provide a accurate information for potential customer.',
    author: 'MRKSC',
    published: '20.2.2020',
    skills: {
      node: '',
      react: '',
      wordpress: 'on',
      server: '',
      database: '',
      javascript: 'on',
      google: 'on',
      css: 'on',
    },
  },
  {
    id: 2,
    localURL: 'Car-companion-app',
    componentName: 'CarApp',
    url: 'Only personal view',
    github: '',
    demo: 'Put-link-here',
    facebook: 'Put-link-here',
    linkedin: 'https://www.linkedin.com/in/mrksc/',
    codePen: 'Put-link-here',
    thumbnail: 'port-thub-two.jpg',
    heading: 'Car companion app',
    subHeading: 'App, backend, server Node.js',
    excerpt: 'I tried to create a application for user where he can monitor his information about a car. The app is monitoring all data about the car like last service check, basic information, future dates which require a user attention as next oil change or STK control. With this project i tried to learn functionality of server, database and user authentication. I have used Node.js, Google Oauth2, Mongodb for the backend of the application and for the frontend classical HTML, CSS and plain JavaScript. I get the overall knowledge how the stuff are connected and how complex is to build a whole application alone.',
    author: 'MRKSC',
    published: '28.4.2019',
    skills: {
      node: 'on',
      react: '',
      wordpress: '',
      server: 'on',
      database: 'on',
      javascript: 'on',
      google: 'on',
      css: 'on',
    },
  },
  {
    id: 3,
    localURL: 'password-generator-app',
    componentName: 'PasswordGenerator',
    url: '',
    github: 'Put-link-here',
    demo: 'Put-link-here',
    facebook: 'Put-link-here',
    linkedin: 'https://www.linkedin.com/in/mrksc/',
    codePen: 'Put-link-here',
    thumbnail: 'port-thub-three.jpg',
    heading: 'Password Generator app',
    subHeading: 'React with dynamic theme and state',
    excerpt: 'The app is a common first project type app names as password generator which generate password under some options. This app was my second experience with react and the purpose of building this app was to get familiar with React basic like State and file structure or styled components and more . The project showed me how great it can be to use a nice framework for building a app. State gives me as developer new look on how to build a applications and control the behavior of the app. After this experience i was ready to go deeper and focus on react for longer. ',
    author: 'MRKSC',
    published: '14.12.2019',
    skills: {
      node: '',
      react: 'on',
      wordpress: '',
      server: '',
      database: '',
      javascript: 'on',
      google: '',
      css: 'on',
    },

  },
];


export default projectData;
